services:
  api:
    build: .
    container_name: urbangraph-api
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - PYTHONUNBUFFERED=1
      - URBANGRAPH_TOKEN=sandoval-enterprise-token-2025

  webapp:
    build: .
    container_name: urbangraph-ui
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - api
    command: streamlit run 5_app_web.py --server.port 8501 --server.address 0.0.0.0
    environment:
      - PYTHONUNBUFFERED=1
